import test from 'node:test';
import assert from 'node:assert/strict';
import {appHarness} from './app-harness.mjs';
async function setup({fail=false}={}){const calls=[],sessions=[{id:'s',title:'Story'}],lore=[];const use=appHarness({globals:{document:{dispatchEvent:e=>calls.push(['notice',e.detail])},CustomEvent:class{constructor(type,v){this.type=type;Object.assign(this,v);}}},stubs:{'auth.js':{currentUid:()=> 'owner'},'sessions.js':{createSession:async(...args)=>{calls.push(['create',...args]);return 's';},updateSession:async(...args)=>calls.push(['publish',...args]),deleteSession:async id=>calls.push(['delete',id]),getSession:async()=>sessions[0],listSessions:async()=>sessions},'messages.js':{getMessages:async()=>[{id:'u',order:1,role:'user',content:'Text'}],addMessagesBulk:async()=>{calls.push(['chunks']);if(fail)throw Error('write failed');}},'lore-store.js':{getLore:async()=>lore,importLore:async(_sid,plan)=>{lore.push(...plan.writes.map(w=>w.data));calls.push(['lore']);}},'ui/memory-ui.js':{download:(...args)=>calls.push(['download',...args])}}});return {api:await use('import-export.js'),calls,lore,sessions};}
const file=(head={})=>({name:'story.jsonl',size:200,text:async()=>[JSON.stringify({character_name:'Story',nera:{version:2,session:head,lore:[{book:'characters',name:'Mira'},null]}}),'null','[1]',JSON.stringify({mes:'Hi',is_user:true})].join('\n')});
test('D5 import publishes only after chunks and normalized lore; no imported revision',async()=>{const h=await setup();await h.api.importSillyTavern(file({historyRevision:999,memory:{autoUpdate:true,sceneFallback:true,updateMaxTokens:32000}}));assert.equal(h.calls[0][2].importing,true);assert.deepEqual(h.calls.slice(0,4).map(c=>c[0]),['create','chunks','lore','publish']);const patch=h.calls[3][2];assert.equal('historyRevision'in patch,false);assert.equal(patch.importing,false);assert.equal(patch.memory.autoUpdate,false);assert.equal(patch.memory.sceneFallback,false);assert.equal(patch.memory.updateMaxTokens,2000);assert.ok(h.lore[0].id);assert.ok(h.lore[0].sections.notes.lines);assert.equal(h.calls.at(-1)[1].droppedLore,1);});
test('D5 failed import stays unpublished and requests resumable cleanup',async()=>{const h=await setup({fail:true});await assert.rejects(h.api.importSillyTavern(file()),/write failed/);assert.deepEqual(h.calls.map(c=>c[0]),['create','chunks','delete']);});
test('R4 null lines are skipped and files over twenty MB rejected before reading',async()=>{const h=await setup();assert.equal(h.api.parseSillyTavernJsonl('null\n'+JSON.stringify({mes:'Hi',is_user:true})).messages.length,1);let read=false;await assert.rejects(h.api.importSillyTavern({size:21*1024*1024,text:async()=>{read=true;}}),/20 MB/);assert.equal(read,false);});
test('P2 account download contains every story, reports progress and cancels without a download',async()=>{const h=await setup(),progress=[];h.sessions.push({id:'b',title:'B'});assert.equal(await h.api.exportAllStories({onProgress:p=>progress.push(p)}),2);const download=h.calls.at(-1);assert.equal(download[0],'download');assert.equal((download[1].match(/neraStorySeparator/g) ?? []).length,2);assert.equal(progress.at(-1).done,2);const controller=new AbortController();h.calls.length=0;await assert.rejects(h.api.exportAllStories({signal:controller.signal,onProgress:()=>controller.abort()}),e=>e.name==='AbortError');assert.equal(h.calls.length,0);});
